[package]
name = "bevy_playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version="0.11", features=["dynamic_linking"]}
bevy-inspector-egui = "0.20.0"
bevy_math = "0.11.3"
